<?php

namespace Tests\Feature;

use App\User;
use Faker\Generator as Faker;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class ViewTest extends TestCase
{
    use DatabaseMigrations;

    private User $user;
    private Faker $faker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->faker = $this->app->make(Faker::class);


        $this->user = factory(User::class)->create();

    }

    public function testHomepage()
    {
        $this->get('/')->assertOk();
    }

    public function testBlogHomepage()
    {
        $this->get('/blog/'.$this->user->name)->assertOk();
    }
}
